# Generated by Django 5.0.6 on 2024-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_accountverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
