# Generated by Django 5.0.6 on 2024-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_accountverification_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='sent_at',
            field=models.DateTimeField(),
        ),
    ]
