# Generated by Django 5.0.6 on 2024-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_accountverification_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
